### ISSUE TITLE
Culture not found for 'en'

### ISSUE THREAD

**Issue by Miuccia7** [azam/jellyfin-plugin-localsubs#3]
Hello,

LocalSubs can't find my subtitle files on a library scan.

For example, my subtitle is in Subs/3_English.srt

The templates are:
Subs/%fn%/%n%_%l%.srt
Subs/%fn%.%l%.srt
Subs/%n%_%l%.srt
Subs/%l%.srt
Subs/%fn%.srt

The log shows this:
```

[2024-01-09 22:18:12.285 +00:00] [ERR] [34] Jellyfin.Plugin.LocalSubs.LocalSubsProvider: Culture not found for "nl"
System.Globalization.CultureNotFoundException: Only the invariant culture is supported in globalization-invariant mode. See https://aka.ms/GlobalizationInvariantMode for more information. (Parameter 'name')
nl is an invalid culture identifier.
   at System.Globalization.CultureInfo.GetCultureInfo(String name)
   at Jellyfin.Plugin.LocalSubs.LocalSubsProvider.Search(SubtitleSearchRequest request, CancellationToken cancellationToken)
[2024-01-09 22:18:12.311 +00:00] [ERR] [34] Jellyfin.Plugin.LocalSubs.LocalSubsProvider: Culture not found for "en"
System.Globalization.CultureNotFoundException: Only the invariant culture is supported in globalization-invariant mode. See https://aka.ms/GlobalizationInvariantMode for more information. (Parameter 'name')
en is an invalid culture identifier.
   at System.Globalization.CultureInfo.GetCultureInfo(String name)
   at Jellyfin.Plugin.LocalSubs.LocalSubsProvider.Search(SubtitleSearchRequest request, CancellationToken cancellationToken)
```

**Comment by Miuccia7** [comment]
Is this relevant?

https://stackoverflow.com/questions/76394279/scaffold-dbcontext-culturenotfoundexception-only-the-invariant-culture-is-sup

**Comment by azam** [comment]
@Miuccia7 
Yeah, most probably it is.
Please see https://github.com/azam/jellyfin-plugin-localsubs/issues/2 for details and possible solution.

**Comment by Miuccia7** [comment]
That's it! Thank you very much, this plugin is fantastic!

I'm on Synology DSM 7.2 Docker, all I had to do was change the DOTNET_SYSTEM_GLOBALIZATION_INVARIANT to 0.

**Comment by Miuccia7** [comment]
That's it! Thank you very much, this plugin is fantastic!

I'm on Synology DSM 7.2 Docker, I had to change the DOTNET_SYSTEM_GLOBALIZATION_INVARIANT variable to 0 in Container Manager.
